FROM node:18 AS build
WORKDIR /app
COPY gpu-frontend ./gpu-frontend
WORKDIR /app/gpu-frontend
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=build /app/gpu-frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
